### ISSUE TITLE
adapt json-resume

### ISSUE THREAD

**Issue by realsnick** [BartoszJarocki/cv#12] opened 2023-12-28 15:26 UTC
https://jsonresume.org/

**Comment by SujithThirumalaisamy** [comment] 2023-12-28 19:13
I would like to work with this. Can you please give me a bit detail? As I think. That link is a standard object. Should we make the whole this based on that standard. Sorry if I was misunderstood. I think this is a pretty big change.

**Comment by realsnick** [comment] 2023-12-28 21:23
@SujithThirumalaisamy you can take a look at my repo https://github.com/realsnick/resume

i think there are a few things here that can be modified...i think your UI should be changed to a theme, and maybe utilize the dev environment, similar to what i have ... i use a nix project

**Comment by thomasdavis** [comment] 2023-12-29 08:43
@realsnick the new jsonresume monorepo uses next+turbo, and this seems to be a decently straightforward react component. 

I might play with the idea of creating an npm package called `jsonresume-theme-cv` (some other name) and then clone this repo into it, setup some build scripts to induce compatibility (that can also convert between the two schemas for now). Will report back on that strategy.

**Comment by BartoszJarocki** [comment] 2024-04-05 21:02
closing as duplicate of #1

**Closed by BartoszJarocki** 2024-04-05 21:02 UTC
